# global config
global:
  scrape_interval: "1m"
  scrape_timeout: "10s"
  evaluation_interval: "1m"

  #alermanager configs
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "alertmanager:9093"
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert.rules"
scrape_configs:
  - job_name: pushgateway
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9091']
  - job_name: crawler
    scrape_interval: 5s
    static_configs:
      - targets: ['crawler-app:8084', 'host.docker.internal:8084', 'localhost:8084']
  # - job_name: event
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['event-app:8083', 'host.docker.internal:8083', 'localhost:8083']
  # - job_name: ticket
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['ticket-app:8082', 'host.docker.internal:8082', 'localhost:8082']
  # - job_name: user-grpc
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['user-app:8081', 'host.docker.internal:8081', 'localhost:8081']
  # - job_name: user-api
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['user-app:8080', 'host.docker.internal:8080', 'localhost:8080']
