// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CloseEventSlot(ctx context.Context, id uuid.UUID) (EventSlot, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	GetEvent(ctx context.Context, id uuid.UUID) (Event, error)
	GetEventSlotsByEventId(ctx context.Context, eventID uuid.UUID) ([]EventSlot, error)
	GetEventSlotsById(ctx context.Context, id uuid.UUID) (EventSlot, error)
	OpenEventSlots(ctx context.Context, arg OpenEventSlotsParams) (EventSlot, error)
	StartEvent(ctx context.Context, id uuid.UUID) (Event, error)
	UpdateEventSlots(ctx context.Context, arg UpdateEventSlotsParams) (EventSlot, error)
}

var _ Querier = (*Queries)(nil)
