// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetTicketsByEventSlotId(ctx context.Context, eventSlotID uuid.UUID) ([]UserTicket, error)
	GetTicketsByUserId(ctx context.Context, buyerID pgtype.UUID) ([]UserTicket, error)
	GetTotalTicketByEventSlot(ctx context.Context, eventSlotID uuid.UUID) (int64, error)
	SellTicket(ctx context.Context, arg SellTicketParams) (UserTicket, error)
}

var _ Querier = (*Queries)(nil)
