// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package domain

import (
	"time"

	"github.com/google/uuid"
)

type CreateEventDto struct {
	EventName    string    `json:"event_name"`
	Note         string    `json:"note"`
	EventOwnerID uuid.UUID `json:"event_owner_id"`
}

type Event struct {
	ID               uuid.UUID        `json:"id"`
	EventName        string           `json:"event_name"`
	Note             string           `json:"note"`
	Revenue          float32          `json:"revenue"`
	Status           string      `json:"status"`
	TotalSoldTickets int32            `json:"total_sold_tickets"`
	EventOwnerID     uuid.UUID        `json:"event_owner_id"`
	Created          time.Time `json:"created"`
	Updated          time.Time `json:"updated"`
}


type CreateEventSlot struct {
	SlotName    string           `json:"slot_name"`
	Description string           `json:"description"`
	Price       float32          `json:"price"`
	Capacity    int32            `json:"capacity"`
	StartTime   time.Time `json:"start_time"`
	EndTime     time.Time `json:"end_time"`
	EventID     uuid.UUID        `json:"event_id"`
}



type EventSlot struct {
	ID          uuid.UUID        `json:"id"`
	SlotName    string           `json:"slot_name"`
	Description string           `json:"description"`
	Price       float32          `json:"price"`
	Capacity    int32            `json:"capacity"`
	Status      string  `json:"status"`
	StartTime   time.Time  `json:"start_time"`
	EndTime     time.Time  `json:"end_time"`
	EventID     uuid.UUID        `json:"event_id"`
	EventName    string           `json:"event_name"`
	Created     time.Time  `json:"created"`
	Updated     time.Time  `json:"updated"`
}
