apiVersion: v1
kind: Service
metadata:
  name: user-app-service  # Name of the service
  labels:
    app: user-app
spec:
  selector:
    app: user-app
  ports:
    - protocol: TCP
      port: 8080 #  port for incoming traffic
      targetPort: 8080 # Port on which the application is running Service‘s pods
      name: http-server
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: grpc-server
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service  # Name of the service
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: redis-server
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service  # Name of the service
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 20241
      targetPort: 5432
      name: postgres-server
  type: NodePort