// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error)
	GetSource(ctx context.Context, id uuid.UUID) (Source, error)
	GetSources(ctx context.Context) ([]Source, error)
	UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error)
}

var _ Querier = (*Queries)(nil)
