// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DbUser struct {
	ID          uuid.UUID        `json:"id"`
	Code        string           `json:"code"`
	Username    string           `json:"username"`
	DisplayName pgtype.Text      `json:"display_name"`
	Password    string           `json:"password"`
	Email       pgtype.Text      `json:"email"`
	Status      bool             `json:"status"`
	Role        int32            `json:"role"`
	Created     pgtype.Timestamp `json:"created"`
	Updated     pgtype.Timestamp `json:"updated"`
}
