// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package domain

import (
	"time"

	"github.com/google/uuid"
)


type EventSlotTickets struct {
	EventSlotId          uuid.UUID      `json:"event_slot_id"`
	Issued        int32         `json:"issued"`
	Total    int32         `json:"total"`
	Created     time.Time      `json:"created"`
	Updated     time.Time      `json:"updated"`
}

type UserTicket struct {
	ID          uuid.UUID        `json:"id"`
	Code        string           `json:"code"`
	EventSlotID uuid.UUID        `json:"event_slot_id"`
	Status      string            `json:"status"`
	Price       float32  `json:"price"`
	Issued     time.Time  `json:"issued"`
	BuyerID     uuid.UUID     `json:"buyer_id"`
}
