definitions:
  domain.CreateEventDto:
    properties:
      event_name:
        type: string
      event_owner_id:
        type: string
      note:
        type: string
    type: object
  domain.CreateEventSlot:
    properties:
      capacity:
        type: integer
      description:
        type: string
      end_time:
        type: string
      event_id:
        type: string
      price:
        type: number
      slot_name:
        type: string
      start_time:
        type: string
    type: object
  domain.Event:
    properties:
      created:
        type: string
      event_name:
        type: string
      event_owner_id:
        type: string
      id:
        type: string
      note:
        type: string
      revenue:
        type: number
      status:
        type: string
      total_sold_tickets:
        type: integer
      updated:
        type: string
    type: object
  domain.EventSlot:
    properties:
      capacity:
        type: integer
      created:
        type: string
      description:
        type: string
      end_time:
        type: string
      event_id:
        type: string
      event_name:
        type: string
      id:
        type: string
      price:
        type: number
      slot_name:
        type: string
      start_time:
        type: string
      status:
        type: string
      updated:
        type: string
    type: object
  domain.Page:
    properties:
      page_events:
        items:
          $ref: '#/definitions/domain.PageEvent'
        type: array
      url:
        type: string
    type: object
  domain.PageEvent:
    properties:
      enter_value:
        type: string
      order:
        type: integer
      parsed_objects:
        items:
          $ref: '#/definitions/domain.PageObject'
        type: array
      selector:
        type: string
      time_sleep:
        type: integer
      type:
        type: string
    type: object
  domain.PageObject:
    properties:
      key:
        type: string
      objects:
        items:
          $ref: '#/definitions/domain.PageObject'
        type: array
      regex_extract:
        type: string
      selector:
        type: string
    type: object
  domain.Source:
    properties:
      data:
        $ref: '#/definitions/domain.WebSite'
      id:
        type: string
      name:
        type: string
    type: object
  domain.WebSite:
    properties:
      pages:
        items:
          $ref: '#/definitions/domain.Page'
        type: array
      url:
        type: string
    type: object
info:
  contact: {}
paths:
  /event:
    post:
      consumes:
      - application/json
      description: Create event
      parameters:
      - description: Event Info
        in: body
        name: arg
        required: true
        schema:
          $ref: '#/definitions/domain.CreateEventDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Event'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create event
      tags:
      - event
  /event/:id/slots:
    get:
      consumes:
      - application/json
      description: get slot of an event by event Id
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.EventSlot'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: get slots of an event
      tags:
      - event
  /event/{id}:
    get:
      consumes:
      - application/json
      description: get event by Id
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Event'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: get an event
      tags:
      - event
  /event/slot:
    post:
      consumes:
      - application/json
      description: create slot for an event
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: string
      - description: Event Slot Info
        in: body
        name: arg
        required: true
        schema:
          $ref: '#/definitions/domain.CreateEventSlot'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.EventSlot'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create slots for an event
      tags:
      - event
  /event/slot/{id}:
    get:
      consumes:
      - application/json
      description: get slot event by event Id
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.EventSlot'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: get slots of an event
      tags:
      - event
  /source:
    post:
      consumes:
      - application/json
      description: Create Source
      parameters:
      - description: Source Info
        in: body
        name: arg
        required: true
        schema:
          $ref: '#/definitions/domain.Source'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Source'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create Source
      tags:
      - Source
  /source/{id}:
    get:
      consumes:
      - application/json
      description: get source by Id
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Source'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: get an source
      tags:
      - source
swagger: "2.0"
