// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package domain

import (
	"database/sql"
	"time"
	"fmt"

	"github.com/google/uuid"
)

type Role int8
const (
    Admin Role = -1
    Buyer Role = 0
    EventOwner Role = 1
)

func (e Role) String() string {
	return fmt.Sprintf("%d", int(e))
}

type User struct {
	ID          uuid.UUID      `json:"id"`
	Code        string         `json:"code"`
	Username    string         `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
	Password    string         `json:"password"`
	Email       sql.NullString `json:"email"`
	Status      bool           `json:"status"`
	Role        int32          `json:"role"`
	Created     time.Time      `json:"created"`
	Updated     time.Time      `json:"updated"`
}
