// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package domain

import (
	"database/sql"
	"time"
	"github.com/google/uuid"
)

type Role string

const (
	Admin      Role = "Admin"
	Buyer      Role = "Buyer"
	EventOwner Role = "EventOwner"
	Seller     Role = "Seller"
)

type User struct {
	ID          uuid.UUID      `json:"ID"`
	Code        string         `json:"code"`
	Username    string         `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
	Password    string         `json:"password"`
	Email       sql.NullString `json:"email"`
	Status      bool           `json:"status"`
	Role        string          `json:"role"`
	Created     time.Time      `json:"created"`
	Updated     time.Time      `json:"updated"`
}

type RawUser struct {
	ID          string      `json:"ID"`
	Code        string         `json:"code"`
	Username    string         `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
	Password    string         `json:"password"`
	Email       sql.NullString `json:"email"`
	Status      bool           `json:"status"`
	Role        string          `json:"role"`
	Created     time.Time      `json:"created"`
	Updated     time.Time      `json:"updated"`
}

type NewUser struct {
	Username    string         `json:"username"`
	DisplayName string `json:"display_name"`
	Password    string         `json:"password"`
	Email       string `json:"email"`
	Role        string          `json:"role"`
}

type UserLogin struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserAccount struct {
	Username    string         `json:"username"`
	DisplayName string `json:"display_name"`
	Email       string `json:"email"`
	Role        string          `json:"role"`
	Token	   string         `json:"token"`
}

