name: Deploy Go App to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.22'

      - name: Build
        run: go build -o user-api cmd/user/main.go

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            echo "Starting deployment..."
            APP_NAME=user-api
            REMOTE_DIR=/home/${{ secrets.EC2_USER }}/app

            # Create remote directory if it doesn't exist
            ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p $REMOTE_DIR"

            # Copy the built executable
            scp -o StrictHostKeyChecking=no $APP_NAME ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:$REMOTE_DIR/$APP_NAME

            # Example: Stop and start the application (adjust as needed)
            ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "pkill -f $APP_NAME && nohup $REMOTE_DIR/$APP_NAME &"

            echo "Deployment complete!"
